export enum GameEvent {
  BOSS_DEAD = 'BOSS_DEAD',
  BOSS_GET_DAMAGE = 'BOSS_GET_DAMAGE',
  UPDATE_BOSS_MESSAGE = 'SET_BOSS_MESSAGE',
  PLAYER_DEAD = 'PLAYER_DEAD',
  PLAYER_GET_DAMAGE = 'PLAYER_GET_DAMAGE',
  UPDATE_PLAYER_INFO = 'UPDATE_PLAYER_INFO',
  GAME_OVER = 'GAME_OVER',
  CLEAR_STAGE = 'CLEAR_STAGE'
}
